sudo: false
dist: trusty
language: node_js
node_js:
  - 12.4.0
install:
  - npm ci
script:
  - npm run check
  - npm test
cache: npm
addons:
  apt:
    # for kerberos and keytar dependencies via mongodb-data-service
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
      - xvfb
      - libsecret-1-dev
      - gnome-keyring
      - python-gnomekeyring
